# --- START OF FILE operator_mode.py ---
import streamlit as st

TUTORIAL_TEXT = """
# Operator Mode Tutorial

---

You are not allow to Launch Public Link IN ANY TIME.

## 1. Understanding the Interface

When you open the web application, you will see the main content in the center of the screen and a sidebar on the left. Here is an overview of each section and how to use it:

### Main Header
- **Title**: The top of the page displays the title **“Agentic OmicVerse 🧬”**.
- **UTC Time**: Next to the title, the current UTC time is shown (refreshes automatically).
- **User**: Next to the time, you’ll see the currently recognized username (defaults to your system username, but can be changed in the Configuration panel).

### The Sidebar
The sidebar contains panels that help you monitor, configure, and extend the system:

1. **System Status**  
   - Displays memory usage, CPU usage, and system uptime.
   - Shows a progress bar reflecting your system’s overall memory usage percentage.

2. **System Health**  
   - Indicates whether the local language model server (Ollama) is running.
   - A green check mark (“Ollama Server is running”) indicates the server is ready; a red alert indicates it is unavailable.

3. **Configuration**  
   - **Select Package**: Choose which package’s documents you want to query locally (e.g., `cellrank_notebooks`, `scanpy_tutorials`, etc.).
   - **Model Settings**:
     - **File Selection Model**: Model used for finding the most relevant files for your query.
     - **Query Processing Model**: Model that generates the final answer from the selected documents.
   - **Rate Limit (seconds)**: Sets how many seconds you must wait between queries to avoid overloading the system.
   - **Username**: Lets you modify the current username displayed in the main header.
   - **Save Configuration**: Applies any changes made above.  

4. **Public Link**  
   - A panel that allows you to open or close an ngrok tunnel.  
   - Clicking **“Launch Public Link”** generates a public URL you can share so others can access your Streamlit app remotely.  
   - Clicking **“Stop Public Link”** closes the ngrok tunnel.

5. **Query History**  
   - Shows a list of your recent local queries (for the RAG-based system), each with an expandable panel.  
   - Each entry includes the package name, query text, timestamp, user, relevant file(s), and the final answer.

6. **Online Search History**  
   - Shows a list of your recent “online” (web) searches performed via Google and Gemini.  
   - Each entry includes your query text, timestamp, user, and the final answer from the online retrieval.

7. **Token Usage**  
   - Displays counters for how many tokens (units of text) have been used as **input** versus **output** throughout your session.  
   - Helpful for monitoring usage if you have local resource or API constraints.

---

## 2. Main Page Features

### “Reset System” Button
- Clears **all** query history (both local and online), resets the rate limiter, and clears internal caches.
- Useful if you want to start fresh.

### Local Query Interface
1. **Text Input Area (“Query Interface 🔍”)**  
   - Type your question or request about the **selected package’s** documents here.  
   - Example: “How do I run RNA velocity analysis in cellrank_notebooks?”

2. **Submit Button (“🚀 Submit”)**  
   - Sends your query to the local RAG system for processing.  
   - Note: If you see a warning to “Please wait X seconds,” it means the rate limiter is active.

3. **Clear History Button (“🗑️ Clear History”)**  
   - Wipes out only the **local** query history shown in the sidebar, but does not affect online search history.  

4. **Results**  
   - After submitting, you’ll see progress updates:
     - **Finding relevant documents**  
     - **Generating answer from annotated scripts**  
     - **Updating history**  
   - Finally, you’ll see:
     - **“Selected document(s)”**: which files the system used to answer your question.
     - **“Local RAG Answer 💡”**: the final response from the language model.

### Online Search Interface
1. **Text Input Area (“Online Search 🌐”)**  
   - Type any query you want to search on the web using Google + Gemini.  
   - Example: “What are the latest improvements in single-cell transcriptomics?”

2. **Search Online Button (“🔎 Search Online”)**  
   - Sends the query to an online model that may retrieve live or recent web data.

3. **Clear Online Search History (“🗑️ Clear Online Search History”)**  
   - Removes all entries in the **online** search history panel.  
   - Does not affect local query history.

4. **Results**  
   - Displays **“Online Search Answer”** with text retrieved and generated by Gemini’s tool-enabled search.  
   - Entry is also recorded in your “Online Search History” in the sidebar.

---

## 3. Step-by-Step Usage

1. **Check System Health**  
   - Confirm Ollama Server is running (sidebar → “System Health”).  
   - If not running, you may see a button **“Start Ollama Server”** in the main area. Click it to launch the server.  
   - Wait a few seconds for it to initialize.

2. **Configure Settings (Optional)**  
   - In the **“Configuration”** panel, pick the desired package (e.g., “cellrank_notebooks”).  
   - Choose which models to use for file selection and query processing.  
   - Adjust the “Rate Limit” slider if you expect to make rapid queries.  
   - Update the “Username” if needed, then click **“Save Configuration.”**

3. **(Optional) Launch a Public Link**  
   - In the **“Public Link”** panel, click **“Launch Public Link”** if you want to share your Streamlit app externally.  
   - The system will generate an ngrok URL you can give to collaborators.  
   - To disable sharing, click **“Stop Public Link.”**

4. **Perform a Local Document Query**  
   - Under **“Query Interface 🔍”**, type your question in the text box.  
   - Click **“🚀 Submit”**.  
   - A progress bar appears, showing the steps to find relevant docs and generate the answer.  
   - Once finished, the relevant files and the final answer are displayed.  
   - This interaction is recorded in the **Query History** sidebar panel.

5. **Perform an Online Search**  
   - Under **“Online Search 🌐”**, type a question that requires web context.  
   - Click **“🔎 Search Online”**.  
   - The system will query Gemini with Google Search enabled, returning a short text answer from the web.  
   - This is recorded in the **Online Search History** sidebar panel.

6. **Revisit or Clear History**  
   - The two separate history panels in the sidebar let you review your past queries and their answers:
     - **Query History** for local doc queries.
     - **Online Search History** for web-based queries.  
   - Click **“🗑️ Clear History”** (main page) to clear local queries, or **“🗑️ Clear Online Search History”** to clear web queries.  
   - If you need a full reset, click **“Reset System”** to remove all history, reset the rate limiter, and clear any caches.

7. **Token Usage**  
   - Keep an eye on the “Token Usage” panel in the sidebar to see how many tokens you’ve used overall (input + output).  
   - This can help you gauge resource usage or potential costs, depending on your environment.

---

## 4. Tips and Troubleshooting

- **Empty Queries**: The app will display an error if you submit an empty query. Provide a meaningful question or statement to process.
- **Rate Limiter**: If the app prompts you to wait a certain number of seconds, it’s preventing too-frequent queries. Be patient or adjust the rate limit in the sidebar’s configuration.
- **Ollama Server Not Detected**: If you get a “server not running” error, ensure you have **ollama** installed and use the “Start Ollama Server” button or manually run `ollama serve` in a terminal.
- **Package Relevance**: If your local query returns irrelevant answers, confirm that you’re querying the correct package or try rephrasing your question.
- **Online Search**: For the online search to work, you must set `GEMINI_API_KEY` in your environment. If it’s not set, you’ll see an error message. 
- **Public Link**: If pyngrok isn’t installed or configured, you won’t be able to launch a public URL. In that case, either install pyngrok or share your app via another method.
- **Reset System**: If you want to wipe everything (including local and online histories) and start over, just click **“Reset System”** and confirm.

---

## 5. Overview of Included Packages

Each “package” you see in the dropdown has its own set of tutorials/notebooks you can query locally:

- **CellRank**: Analyzes cellular dynamics, focusing on fate decisions over time.
- **Scanpy**: A comprehensive toolkit for single-cell gene expression data analysis (preprocessing, clustering, visualization).
- **scvi-tools**: Uses deep learning for single-cell data integration and cell-type identification.
- **Spateo**: Focuses on spatial transcriptomics analysis (how gene expression varies within tissue structure).
- **Squidpy**: Offers advanced spatial molecular data analysis, integrating well with Scanpy.
- **OmicVerse**: A broader ecosystem for multi-omics analyses, including single-cell and bulk transcriptomics.

---

**Enjoy exploring various OmicVerse tutorials and notebooks, and remember to use Operator Mode for a complete overview of the system!**
"""

def show_tutorial():
    """
    Display the Operator Mode tutorial in Streamlit.
    """
    # You can style this any way you like, e.g. st.write, st.markdown, or st.html.
    st.markdown(TUTORIAL_TEXT)
# --- END OF FILE operator_mode.py ---