"""Thin wrapper around ``pyscdblfinder`` for omicverse's QC pipeline.

Exposes a single ``scdblfinder(adata, ...)`` function used by ``ov.pp.qc``
with ``doublets_method='scdblfinder'``. Writes two columns to
``adata.obs`` so the existing `filter_doublets` codepath (which keys off
``predicted_doublet``) works unchanged:

    * ``predicted_doublet`` — bool mask
    * ``doublet_score``     — xgboost doublet probability (0..1)

plus two extra diagnostic columns:

    * ``scdblfinder_doublet`` — same bool, under a backend-specific name
    * ``scdblfinder_score``   — same score, under a backend-specific name

Differences vs DoubletFinder / scrublet:

- scDblFinder uses an xgboost classifier on kNN + cxds features, so it
  tends to flag slightly more cells than scrublet and agrees ~95-97%
  with the canonical R scDblFinder on real 10x data.
- Because xgboost is trained per-call, scores are not deterministic
  across R/Python even with the same seed; see pyscdblfinder's README
  for why. Classifications are the stable comparison surface.
"""
from __future__ import annotations

from typing import Optional

import anndata
import numpy as np


def scdblfinder(
    adata: anndata.AnnData,
    *,
    dbr: Optional[float] = None,
    dbr_per1k: float = 0.008,
    dims: int = 20,
    n_features: int = 1352,
    n_artificial: Optional[int] = None,
    prop_random: float = 0.0,
    k: Optional[int | list[int]] = None,
    iter: int = 3,
    nrounds: float | int = 0.25,
    max_depth: int = 4,
    random_state: int = 1234,
    batch_key: Optional[str] = None,
    clusters: Optional[str] = None,
) -> anndata.AnnData:
    """Run pyscdblfinder and write calls to ``adata.obs``.

    Parameters
    ----------
    dbr : expected doublet rate. When ``None``, inferred from the 10x
        Chromium default: ``dbr_per1k * n_cells / 1000``.
    dims : number of principal components for the kNN graph.
    n_features : number of top-variance genes to keep for PCA.
    n_artificial : number of artificial doublets to synthesize. When
        ``None`` it's chosen per the R defaults
        (``min(25000, max(1500, ceil(n_cells*0.8), 10*n_clusters^2))``).
    clusters : name of an ``obs`` column holding cluster labels. If set,
        artificial doublets are generated by inter-cluster mixing rather
        than fully random pairs (matches R's ``clusters=`` argument).
    batch_key : when given, scDblFinder is run independently per batch.
    """
    try:
        from pyscdblfinder import ScDblFinder
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "pyscdblfinder is required for doublets_method='scdblfinder'. "
            "Install it with `pip install pyscdblfinder`."
        ) from exc

    effective_dbr = dbr if dbr is not None else (dbr_per1k * adata.n_obs / 1000.0)

    def _run_one(sub: anndata.AnnData) -> tuple[np.ndarray, np.ndarray]:
        sdf = ScDblFinder(sub.copy(), random_state=random_state)
        sdf.run(
            dbr=effective_dbr,
            dims=dims,
            n_features=min(n_features, sub.n_vars),
            artificial_doublets=n_artificial,
            prop_random=prop_random,
            k=k,
            iter=iter,
            nrounds=nrounds,
            max_depth=max_depth,
            clusters=clusters if (clusters is not None and clusters in sub.obs.columns) else None,
            verbose=False,
        )
        cls = sdf.adata.obs["scDblFinder_class"].values
        score = sdf.adata.obs["scDblFinder_score"].astype(float).values
        return (cls == "doublet"), score

    predicted = np.zeros(adata.n_obs, dtype=bool)
    scores = np.zeros(adata.n_obs, dtype=np.float64)

    if batch_key is None or batch_key not in adata.obs.columns:
        predicted, scores = _run_one(adata)
    else:
        for batch in adata.obs[batch_key].unique():
            mask = (adata.obs[batch_key] == batch).values
            sub = adata[mask].copy()
            p, s = _run_one(sub)
            predicted[mask] = p
            scores[mask] = s

    adata.obs["predicted_doublet"] = predicted
    adata.obs["doublet_score"] = scores
    adata.obs["scdblfinder_doublet"] = predicted
    adata.obs["scdblfinder_score"] = scores
    return adata
