"""
OVAgent harness contracts, traces, replay, and cleanup helpers.
"""

from .cleanup import CleanupFinding, CleanupReport, HarnessCleaner
from .contracts import (
    HARNESS_EVENT_TYPES,
    STREAM_EVENT_TYPES,
    ArtifactRef,
    ApprovalRequest,
    HarnessEvent,
    HarnessCapabilities,
    HarnessEventType,
    RunTrace,
    ScenarioResult,
    ScenarioSpec,
    StepTrace,
    build_stream_event,
    coerce_usage_payload,
    hash_code_block,
    make_approval_id,
    make_step_id,
    make_trace_id,
    make_turn_id,
)
from .trace_store import RunTraceRecorder, RunTraceStore, ScenarioRunner
from .server_cli import (
    SERVER_ONLY_ENV,
    dump_json,
    load_trace_payload,
    make_trace_store,
    require_server_only_mode,
    run_cleanup,
    run_scenario,
    summarize_trace,
)
from .runtime_state import (
    BackgroundTaskHandle,
    PlanModeState,
    QuestionRecord,
    RuntimeStateManager,
    SessionRuntimeState,
    TaskOutputChunk,
    TaskRecord,
    WorktreeMetadata,
    create_runtime_state_manager,
    runtime_state,
)
from .tool_catalog import (
    CLAUDE_CODE_TOOLS,
    CORE_TOOL_NAMES,
    DEFERRED_TOOL_NAMES,
    ToolCatalog,
    ToolDefinition,
    ToolMatch,
    ToolSearchResult,
    get_default_loaded_tool_names,
    get_default_tool_catalog,
    get_tool_spec,
    get_visible_tool_schemas,
    normalize_tool_name,
    resolve_tool_search,
    resolve_tool_name,
)

StreamEvent = HarnessEvent
StreamEventType = HarnessEventType

__all__ = [
    "HARNESS_EVENT_TYPES",
    "STREAM_EVENT_TYPES",
    "ArtifactRef",
    "ApprovalRequest",
    "HarnessEvent",
    "HarnessCapabilities",
    "HarnessEventType",
    "StreamEvent",
    "StreamEventType",
    "RunTrace",
    "RunTraceRecorder",
    "RunTraceStore",
    "ScenarioSpec",
    "ScenarioResult",
    "ScenarioRunner",
    "StepTrace",
    "CleanupFinding",
    "CleanupReport",
    "HarnessCleaner",
    "BackgroundTaskHandle",
    "PlanModeState",
    "QuestionRecord",
    "RuntimeStateManager",
    "SessionRuntimeState",
    "TaskOutputChunk",
    "TaskRecord",
    "WorktreeMetadata",
    "runtime_state",
    "create_runtime_state_manager",
    "CLAUDE_CODE_TOOLS",
    "CORE_TOOL_NAMES",
    "DEFERRED_TOOL_NAMES",
    "ToolCatalog",
    "ToolDefinition",
    "ToolMatch",
    "ToolSearchResult",
    "get_default_loaded_tool_names",
    "get_default_tool_catalog",
    "get_tool_spec",
    "get_visible_tool_schemas",
    "normalize_tool_name",
    "resolve_tool_search",
    "resolve_tool_name",
    "SERVER_ONLY_ENV",
    "build_stream_event",
    "coerce_usage_payload",
    "dump_json",
    "hash_code_block",
    "load_trace_payload",
    "make_approval_id",
    "make_trace_store",
    "make_step_id",
    "make_trace_id",
    "make_turn_id",
    "require_server_only_mode",
    "run_cleanup",
    "run_scenario",
    "summarize_trace",
]
