# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NetEncoding

class TypedArray(object):
    NONE = 0
    Int32Array = 1
    Uint32Array = 2
    Float32Array = 3
    Float64Array = 4
    JSONEncodedArray = 5
