"""BioContext — biomedical knowledge tools for OmicVerse."""

from ._tools import (
    call_tool,
    list_tools,
    query_uniprot,
    get_uniprot_id,
    query_alphafold,
    get_ensembl_id,
    query_interpro,
    search_interpro,
    query_string,
    query_hpa,
    query_reactome,
    query_go,
    query_panglaodb,
    search_literature,
    search_preprints,
    get_fulltext,
    query_opentargets,
    search_clinical_trials,
    search_drugs,
    query_efo,
    query_chebi,
    query_cell_ontology,
    search_pride,
)
from ._client import BioContextClient, get_client

__all__ = [
    "call_tool",
    "list_tools",
    "query_uniprot",
    "get_uniprot_id",
    "query_alphafold",
    "get_ensembl_id",
    "query_interpro",
    "search_interpro",
    "query_string",
    "query_hpa",
    "query_reactome",
    "query_go",
    "query_panglaodb",
    "search_literature",
    "search_preprints",
    "get_fulltext",
    "query_opentargets",
    "search_clinical_trials",
    "search_drugs",
    "query_efo",
    "query_chebi",
    "query_cell_ontology",
    "search_pride",
    "BioContextClient",
    "get_client",
]
