"""Shared fixed copy for Jarvis channel command responses."""
from __future__ import annotations

from .channel_language import tr


def render_start_text(user_text: str = "", *, html: bool = False) -> str:
    if html:
        return tr(
            user_text,
            en=(
                "👋  <b>OmicVerse Jarvis</b>\n"
                "────────────\n"
                "A mobile single-cell analysis assistant.\n\n"
                "<b>Quick Start</b>\n"
                "1. Upload a <code>.h5ad</code> file to the workspace via <code>scp</code> or <code>sftp</code>\n"
                "2. Use <code>/workspace</code> and then <code>/load</code> to open it\n"
                "3. Send a request such as:\n"
                "   <i>Run QC with nUMI&gt;500 and mito&lt;0.2, then normalize and build UMAP</i>\n\n"
                "<b>Data Commands</b>\n"
                "<code>/workspace</code>  View workspace\n"
                "<code>/ls</code>         List files\n"
                "<code>/find</code>       Search files\n"
                "<code>/load</code>       Load data\n"
                "<code>/shell</code>      Run whitelisted shell commands\n\n"
                "<b>Session Commands</b>\n"
                "<code>/kernel</code>     Current kernel status\n"
                "<code>/kernel ls</code>  List kernels\n"
                "<code>/kernel new x</code> Create and switch kernel\n"
                "<code>/kernel use x</code> Switch kernel\n"
                "<code>/memory</code>     Analysis history\n"
                "<code>/usage</code>      Token usage\n"
                "<code>/model</code>      Switch model\n"
                "<code>/status</code>     Data status\n"
                "<code>/save</code>       Export current.h5ad\n"
                "<code>/cancel</code>     Cancel the current analysis\n"
                "<code>/reset</code>      Reset the session\n"
            ),
            zh=(
                "👋  <b>OmicVerse Jarvis</b>\n"
                "────────────\n"
                "移动端单细胞分析助手。\n\n"
                "<b>快速开始</b>\n"
                "1. 通过 <code>scp</code> 或 <code>sftp</code> 上传 <code>.h5ad</code> 到 workspace\n"
                "2. 使用 <code>/workspace</code> 和 <code>/load</code> 打开它\n"
                "3. 发送类似下面的请求：\n"
                "   <i>质控 nUMI&gt;500 且 mito&lt;0.2，然后标准化并构建 UMAP</i>\n\n"
                "<b>数据命令</b>\n"
                "<code>/workspace</code>  查看 workspace\n"
                "<code>/ls</code>         列出文件\n"
                "<code>/find</code>       搜索文件\n"
                "<code>/load</code>       加载数据\n"
                "<code>/shell</code>      运行白名单 shell 命令\n\n"
                "<b>会话命令</b>\n"
                "<code>/kernel</code>     当前 kernel 状态\n"
                "<code>/kernel ls</code>  列出 kernels\n"
                "<code>/kernel new x</code> 新建并切换 kernel\n"
                "<code>/kernel use x</code> 切换 kernel\n"
                "<code>/memory</code>     分析历史\n"
                "<code>/usage</code>      Token 用量\n"
                "<code>/model</code>      切换模型\n"
                "<code>/status</code>     数据状态\n"
                "<code>/save</code>       导出 current.h5ad\n"
                "<code>/cancel</code>     取消当前分析\n"
                "<code>/reset</code>      重置会话\n"
            ),
        )

    return tr(
        user_text,
        en=(
            "OmicVerse Jarvis\n"
            "----------------\n"
            "A mobile single-cell analysis assistant.\n\n"
            "Quick Start:\n"
            "1. Upload a .h5ad file to the workspace via scp or sftp.\n"
            "2. Use /workspace and then /load to open it.\n"
            "3. Send a request such as: Run QC with nUMI>500 and mito<0.2, then normalize and build UMAP.\n\n"
            "Data Commands:\n"
            "/workspace Show the workspace\n"
            "/ls [path] List files\n"
            "/find <pattern> Search files\n"
            "/load <filename> Load data\n"
            "/shell <command> Run whitelisted shell commands\n\n"
            "Session Commands:\n"
            "/kernel | /kernel ls | /kernel new <name> | /kernel use <name>\n"
            "/memory Analysis history\n"
            "/usage Token usage\n"
            "/model [name] Show or switch model\n"
            "/status Current status\n"
            "/save Export current.h5ad\n"
            "/cancel Cancel the current analysis\n"
            "/reset Reset the session"
        ),
        zh=(
            "OmicVerse Jarvis\n"
            "----------------\n"
            "移动端单细胞分析助手。\n\n"
            "快速开始:\n"
            "1. 通过 scp 或 sftp 上传 .h5ad 文件到 workspace。\n"
            "2. 使用 /workspace 和 /load 打开它。\n"
            "3. 发送类似下面的请求：质控 nUMI>500 且 mito<0.2，然后标准化并构建 UMAP。\n\n"
            "数据命令:\n"
            "/workspace 查看 workspace\n"
            "/ls [path] 列出文件\n"
            "/find <pattern> 搜索文件\n"
            "/load <filename> 加载数据\n"
            "/shell <command> 运行白名单 shell 命令\n\n"
            "会话命令:\n"
            "/kernel | /kernel ls | /kernel new <name> | /kernel use <name>\n"
            "/memory 分析历史\n"
            "/usage Token 用量\n"
            "/model [name] 查看或切换模型\n"
            "/status 当前状态\n"
            "/save 导出 current.h5ad\n"
            "/cancel 取消当前分析\n"
            "/reset 重置会话"
        ),
    )


def render_help_text(user_text: str = "", *, html: bool = False) -> str:
    if html:
        return tr(
            user_text,
            en=(
                "📚  <b>User Guide</b>\n"
                "────────────\n"
                "<b>Analysis Examples</b>\n"
                "• <code>QC with nUMI&gt;500 and mito&lt;0.2</code>\n"
                "• <code>Normalize, find HVGs, PCA, UMAP</code>\n"
                "• <code>Leiden clustering resolution=0.5</code>\n"
                "• <code>Differential expression cluster 1 vs 2</code>\n"
                "• <code>GO enrichment for cluster 0</code>\n\n"
                "<b>Data Management</b>\n"
                "• <code>/workspace</code> — workspace overview\n"
                "• <code>/ls [path]</code> — list files\n"
                "• <code>/find &lt;pattern&gt;</code> — search files\n"
                "• <code>/load &lt;filename&gt;</code> — load data\n"
                "• <code>/shell &lt;command&gt;</code> — run whitelisted shell commands\n\n"
                "<b>Session Management</b>\n"
                "• <code>/kernel</code> — kernel health and prompt budget\n"
                "• <code>/kernel ls</code> — list kernels\n"
                "• <code>/kernel new name</code> — create and switch kernel\n"
                "• <code>/kernel use name</code> — switch kernel\n"
                "• <code>/memory</code> — recent analysis history\n"
                "• <code>/usage</code> — latest token usage\n"
                "• <code>/model [name]</code> — view or switch model\n"
                "• <code>/status</code> — current data status\n"
                "• <code>/save</code> — export <code>current.h5ad</code>\n"
                "• <code>/cancel</code> — cancel the current analysis\n"
                "• <code>/reset</code> — reset the session and restart the kernel\n\n"
                "<b>Custom Instructions</b>\n"
                "Create an <code>AGENTS.md</code> file in the workspace to inject persistent preferences."
            ),
            zh=(
                "📚  <b>使用指南</b>\n"
                "────────────\n"
                "<b>分析示例</b>\n"
                "• <code>质控 nUMI&gt;500 且 mito&lt;0.2</code>\n"
                "• <code>标准化、高变基因、PCA、UMAP</code>\n"
                "• <code>Leiden 聚类 resolution=0.5</code>\n"
                "• <code>差异表达 cluster 1 vs 2</code>\n"
                "• <code>cluster 0 的 GO 富集分析</code>\n\n"
                "<b>数据管理</b>\n"
                "• <code>/workspace</code> — workspace 概览\n"
                "• <code>/ls [path]</code> — 列出文件\n"
                "• <code>/find &lt;pattern&gt;</code> — 搜索文件\n"
                "• <code>/load &lt;filename&gt;</code> — 加载数据\n"
                "• <code>/shell &lt;command&gt;</code> — 运行白名单 shell 命令\n\n"
                "<b>会话管理</b>\n"
                "• <code>/kernel</code> — kernel 状态和 prompt 预算\n"
                "• <code>/kernel ls</code> — 列出 kernels\n"
                "• <code>/kernel new name</code> — 新建并切换 kernel\n"
                "• <code>/kernel use name</code> — 切换 kernel\n"
                "• <code>/memory</code> — 最近分析历史\n"
                "• <code>/usage</code> — 最近一次 token 用量\n"
                "• <code>/model [name]</code> — 查看或切换模型\n"
                "• <code>/status</code> — 当前数据状态\n"
                "• <code>/save</code> — 导出 <code>current.h5ad</code>\n"
                "• <code>/cancel</code> — 取消当前分析\n"
                "• <code>/reset</code> — 重置会话并重启 kernel\n\n"
                "<b>自定义指令</b>\n"
                "在 workspace 中创建 <code>AGENTS.md</code> 文件以注入持久偏好。"
            ),
        )

    return tr(
        user_text,
        en=(
            "OmicVerse Jarvis\n"
            "----------------\n"
            "Analysis Examples:\n"
            "- QC with nUMI>500 and mito<0.2\n"
            "- Normalize, find HVGs, PCA, UMAP\n"
            "- Leiden clustering resolution=0.5\n"
            "- Differential expression cluster 1 vs 2\n"
            "- GO enrichment for cluster 0\n\n"
            "Data Management:\n"
            "/workspace Workspace overview\n"
            "/ls [path] List files\n"
            "/find <pattern> Search files\n"
            "/load <filename> Load data\n"
            "/shell <command> Run whitelisted shell commands\n\n"
            "Session Management:\n"
            "/kernel | /kernel ls | /kernel new <name> | /kernel use <name>\n"
            "/memory Analysis history\n"
            "/usage Token usage\n"
            "/model [name] Show or switch model\n"
            "/status Current status\n"
            "/save Export current.h5ad\n"
            "/cancel Cancel the current analysis\n"
            "/reset Reset the session\n\n"
            "Custom Instructions:\n"
            "Create an AGENTS.md file in the workspace to inject persistent preferences."
        ),
        zh=(
            "OmicVerse Jarvis\n"
            "----------------\n"
            "分析示例:\n"
            "- 质控 nUMI>500 且 mito<0.2\n"
            "- 标准化、高变基因、PCA、UMAP\n"
            "- Leiden 聚类 resolution=0.5\n"
            "- 差异表达 cluster 1 vs 2\n"
            "- cluster 0 的 GO 富集分析\n\n"
            "数据管理:\n"
            "/workspace Workspace 概览\n"
            "/ls [path] 列出文件\n"
            "/find <pattern> 搜索文件\n"
            "/load <filename> 加载数据\n"
            "/shell <command> 运行白名单 shell 命令\n\n"
            "会话管理:\n"
            "/kernel | /kernel ls | /kernel new <name> | /kernel use <name>\n"
            "/memory 分析历史\n"
            "/usage Token 用量\n"
            "/model [name] 查看或切换模型\n"
            "/status 当前状态\n"
            "/save 导出 current.h5ad\n"
            "/cancel 取消当前分析\n"
            "/reset 重置会话\n\n"
            "自定义指令:\n"
            "在 workspace 中创建 AGENTS.md 文件以注入持久偏好。"
        ),
    )
